# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chris Barnes - Digital Product Designer
email: chris@chrisbarnes.co
description: > # this means to ignore newlines until "baseurl:"
  Portfolio of Chris Barnes. A digital designer from the UK.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chrisbarnes.co" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/

# sass settings
sass:
    sass_dir: _sass
    style: compressed

plugins:
  - jekyll-sitemap
